//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoCastle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int OrderID { get; set; }
        public int InvoiceType { get; set; }
        public string InvoiceHeading { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int TotalPrice { get; set; }
        public int TaxRate { get; set; }
        public int Tax { get; set; }
        public string Note { get; set; }
        public string Drawer { get; set; }
        public string CompanyNumber { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int AddedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
