//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoCastle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShoppingCar
    {
        public int CarID { get; set; }
        public int isLogin { get; set; }
        [Display(Name = "會員編號")]
        public Nullable<int> MemberID { get; set; }
        [Display(Name = "訂購人")]
        public string OrderName { get; set; }
        [Display(Name = "收件人")]
        public string ShipName { get; set; }
        [Display(Name = "連絡電話")]
        public string PhoneNumber { get; set; }
        [Display(Name = "收件地址")]
        public string ShippingAddress { get; set; }
        [Display(Name = "寄送方式")]
        public Nullable<int> Delivery { get; set; }
        [Display(Name = "運費")]
        public Nullable<int> ShippingCost { get; set; }
        [Display(Name = "訂單金額")]
        public Nullable<int> TotalAmount { get; set; }
        [Display(Name = "付款方式")]
        public Nullable<int> Payment { get; set; }
        [Display(Name = "預計收件日期")]
        public Nullable<System.DateTime> RequiredDate { get; set; }
        [Display(Name = "新增日期")]
        public Nullable<System.DateTime> AddedDate { get; set; }
        [Display(Name = "修改日期")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [Display(Name = "統一編號")]
        public string CompanyNumber { get; set; }
        [Display(Name = "公司抬頭")]
        public string InvoiceHeading { get; set; }
        [Display(Name = "發票種類")]
        public Nullable<int> InvoiceType { get; set; }
    
        public virtual ShoppingDetail ShoppingDetail { get; set; }
    }
}
